### ISSUE TITLE
Repository description is unnecessarily self deprecating

### ISSUE THREAD

**Issue by iankronquist** [edunham/pleaselicense#1]
You won't be after finishing this project.
Also, someone desperately needs to write a blog post about Github OAuth using ajax.
http://en.wikipedia.org/wiki/Impostor_syndrome

**Comment by edunham** [comment]
...>.> sorry. i fixed it now that the thing is actually working. 

for the historical record it was all "I HAS THE DUMB AT YAVASCRIPTS" and i put it in place about [here](https://github.com/edunham/pleaselicense/commit/01edb0b9568047f07f508ae39eeebd3579e9403c) at which time it was completely true.
